language: swift
xcode_project: LibWally.xcodeproj
xcode_scheme: LibWally
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone XÊ€
osx_image: xcode11.2

cache: ccache

install:
  - swift --version
  - brew install gnu-sed ccache
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - ./build-libwally.sh -s
