name: Build Frameworks
  contents: read
  statuses: read
  pull-requests: read
  actions: read
  checks: write
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"
jobs:
  build:
    name: Build (${{ matrix.configuration['platform'] }})
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        configuration:
        - scheme: App (iOS)
          destination: generic/platform=iOS
          platform: iOS
          sdk-name: iphoneos
        - scheme: App (iOS)
          destination: platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro
          platform: iOS Simulator
          sdk-name: iphonesimulator
          xcode-unit-test: LibWallyTests
        - scheme: App (macOS)
          destination: platform=macOS
          platform: macOS
          sdk-name: macos
          xcode-unit-test: LibWallyTests
          gradle-test: macosX64Test
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Import Certificate
      uses: ./.github/actions/import-cert
      with:
        certificate: ${{ secrets.DEVELOPER_CERT }}
        password: ${{ secrets.DEVELOPER_CERT_PASSWORD }}
    - name: Build
      id: build
      uses: ./.github/actions/build-for-testing
      with:
        scheme: ${{ matrix.configuration['scheme'] }}
        destination: ${{ matrix.configuration['destination'] }}
        app-store-key: ${{ secrets.APPSTORE_KEY }}
        app-store-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        app-store-key-issuer-id: ${{ secrets.APPSTORE_KEY_ISSUER_ID }}
    - name: Xcode Unit Test
      if: ${{ matrix.configuration['xcode-unit-test'] != '' }}
      continue-on-error: true
      uses: ./.github/actions/test-without-building
      with:
        scheme: ${{ matrix.configuration['scheme'] }}
        destination: ${{ matrix.configuration['destination'] }}
        test-plan: ${{ matrix.configuration['xcode-unit-test'] }}
        artifact-prefix: unit-tests-${{ matrix.configuration['sdk-name'] }}
        check-name: Xcode Unit Tests (${{ matrix.configuration['platform'] }})
